# Generated by Django 3.1.7 on 2022-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220213_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.JSONField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Предзаказ'), (1, 'Новый'), (2, 'Подготовка'), (3, 'Выполнен'), (4, 'Отменен')], default=0, max_length=10),
        ),
    ]
