# Generated by Django 3.1.7 on 2022-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220213_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Предзаказ'), (1, 'Новый'), (2, 'Подготовка'), (3, 'Выполнен'), (4, 'Отменен')], default=0),
        ),
    ]
