# Generated by Django 3.1.7 on 2022-02-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200224_1731'),
        ('product', '0009_cartitem_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=256, verbose_name='Чат id')),
                ('name', models.CharField(max_length=256)),
                ('users', models.ManyToManyField(to='bot.TelegramUser')),
            ],
        ),
    ]
