# Generated by Django 3.1.7 on 2022-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Наличные'), (1, 'На карту')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Предзаказ'), (1, 'Новый'), (2, 'Готовка'), (3, 'Отправлен'), (4, 'Выполнен'), (5, 'Отменен')], default=0),
        ),
    ]
