# Generated by Django 3.1.7 on 2022-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220214_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128, unique=True)),
                ('text_ru', models.CharField(blank=True, max_length=512, null=True)),
                ('text_uz', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
