# Generated by Django 3.1.7 on 2022-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='group',
            field=models.IntegerField(choices=[(1, 'Кнопка'), (2, 'Сообщение')], default=1),
        ),
    ]
