# Generated by Django 3.1.7 on 2022-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200224_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=64),
        ),
    ]
